export const APPOINTMENTS = [
  {
    id: "0001",
    case: "Dog Bite",
    description: "Patient bitten by a stray dog on the right leg.",
    branch: "Downtown Clinic",
    doctor: "Dr. Smith",
    status: "Pending",
    createdAt: "2024-08-15 01:25:49.379",
  },
  {
    id: "0002",
    case: "Cat Scratch",
    description: "Patient scratched by a cat on the left arm.",
    branch: "Northside Clinic",
    doctor: "Dr. Johnson",
    status: "Completed",
    createdAt: "2024-08-14 11:15:30.432",
  },
  {
    id: "0003",
    case: "Snake Bite",
    description: "Patient bitten by a snake on the right foot.",
    branch: "West End Clinic",
    doctor: "Dr. Williams",
    status: "Completed",
    createdAt: "2024-08-13 08:45:12.978",
  },
  {
    id: "0004",
    case: "Bat Bite",
    description: "Patient bitten by a bat on the neck.",
    branch: "Eastside Clinic",
    doctor: "Dr. Davis",
    status: "Pending",
    createdAt: "2024-08-12 09:30:55.134",
  },
  {
    id: "0005",
    case: "Rat Bite",
    description: "Patient bitten by a rat on the left hand.",
    branch: "Central Clinic",
    doctor: "Dr. Brown",
    status: "Completed",
    createdAt: "2024-08-11 07:22:47.519",
  },
];
